#!/usr/bin/env bash

# Function to display information for a specific subdomain
display_info() {
    subdomain=$1
    domain=$2
    record_type=$(dig +short $subdomain.$domain | awk '{ print $4 }')
    destination=$(dig +short $subdomain.$domain)
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check if both domain and subdomain parameters are passed
if [ $# -eq 2 ]; then
    display_info $2 $1
else
    # Default subdomains to audit
    subdomains=("www" "lb-01" "web-01" "web-02")

    # Loop through subdomains and display information
    for subdomain in "${subdomains[@]}"
    do
        display_info $subdomain $1
    done
fi
