#!/bin/bash

# Function to display information for a specific subdomain
display_info() {
    subdomain=$1
    domain=$2
    dig_output=$(dig +short $subdomain.$domain)
    echo "The subdomain $subdomain is a $(echo "$dig_output" | awk 'NR==1{ print $4 }') record and points to $dig_output"
}

# Default subdomains to audit
subdomains=("www" "lb-01" "web-01" "web-02")

# Check if both domain and subdomain parameters are passed
if [ $# -eq 2 ]; then
    display_info $2 $1
else
    # Loop through subdomains and display information
    for subdomain in "${subdomains[@]}"
    do
        display_info $subdomain $1
    done
fi
