#!/usr/bin/env bash

# Bash script that transfers a file from our client to a server:

# curl -sL "$1" -X PUT -d @"$2" -H "Content-Type: text/plain"



if [ "$#" -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh_key="$4"

# Use scp to transfer the file to the server
scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

echo "File transfer complete!"


