#!/usr/bin/env bash
# This script installs nginx web server on a server

# Update package list and install nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Set nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Create the HTML file with "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Restart nginx
sudo /etc/init.d/nginx restart
