#!/usr/bin/env bash
# install nginx on your web-01 server
# Nginx should be listening on port 80

apt-get update
apt-get -y install nginx

# chheck if nginx is running and listening on port 80 with netstat


# allow nginx traffic through the firewall
sudo ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
service nginx restart