#!/usr/bin/env bash
# script to find out what is stopig nginx from listening on port 80
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
sudo service nginx restart
sudo pkill -o nginx