#!/bin/bash

# Update package lists and install ufw
sudo apt-get update
sudo apt-get install ufw -y

# Set the default incoming policy to deny
sudo ufw default deny incoming

# Allow incoming traffic on port 22 (SSH)
sudo ufw allow 22/tcp

# Allow incoming traffic on port 443 (HTTPS SSL)
sudo ufw allow 443/tcp

# Allow incoming traffic on port 80 (HTTP)
sudo ufw allow 80/tcp

# Enable ufw
sudo ufw enable
