#!/bin/bash

# Generate RSA key pair
ssh-keygen -t rsa -b 4096 -f school -N betty

# Check if key pair was successfully created
if [ $? -eq 0 ]; then
    echo "RSA key pair created successfully!"
else
    echo "Error creating RSA key pair."
fi
