#!/bin/bash

# Generate an RSA key pair with 4096 bits, named "school"
ssh-keygen -b 4096 -t rsa -f ~/.ssh/school

# Protect the key with the passphrase "betty"
ssh-keygen -p -P "" -N betty -f ~/.ssh/school
