#!/usr/bin/env bash
# script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.

nano ~/.ssh/config
Host 132314-web-01
    HostName 54.90.52.194
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no

